//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GuncelYazılımCase.Module.BusinessObjects.Database
{

    public partial class DboCases : XPObject
    {
        string fCaseName;
        public string CaseName
        {
            get { return fCaseName; }
            set { SetPropertyValue<string>(nameof(CaseName), ref fCaseName, value); }
        }
        string fCaseSubject;
        public string CaseSubject
        {
            get { return fCaseSubject; }
            set { SetPropertyValue<string>(nameof(CaseSubject), ref fCaseSubject, value); }
        }
        DateTime fCaseCreationDate;
        public DateTime CaseCreationDate
        {
            get { return fCaseCreationDate; }
            set { SetPropertyValue<DateTime>(nameof(CaseCreationDate), ref fCaseCreationDate, value); }
        }
        DateTime fCaseSolveDate;
        public DateTime CaseSolveDate
        {
            get { return fCaseSolveDate; }
            set { SetPropertyValue<DateTime>(nameof(CaseSolveDate), ref fCaseSolveDate, value); }
        }
        string fCaseChangeReason;
        public string CaseChangeReason
        {
            get { return fCaseChangeReason; }
            set { SetPropertyValue<string>(nameof(CaseChangeReason), ref fCaseChangeReason, value); }
        }
        DboStatus fStatus;
        [Association(@"CasesReferencesStatus")]
        public DboStatus Status
        {
            get { return fStatus; }
            set { SetPropertyValue<DboStatus>(nameof(Status), ref fStatus, value); }
        }
        DboCustomers fCaseCustomer;
        [Association(@"CasesReferencesCustomers")]
        public DboCustomers CaseCustomer
        {
            get { return fCaseCustomer; }
            set { SetPropertyValue<DboCustomers>(nameof(CaseCustomer), ref fCaseCustomer, value); }
        }
        DboEmployee fEmployee;
        [Association(@"DboCasesReferencesDboEmployee")]
        public DboEmployee Employee
        {
            get { return fEmployee; }
            set { SetPropertyValue<DboEmployee>(nameof(Employee), ref fEmployee, value); }
        }
        DboCaseType fCaseType;
        [Association(@"DboCasesReferencesDboCaseType")]
        public DboCaseType CaseType
        {
            get { return fCaseType; }
            set { SetPropertyValue<DboCaseType>(nameof(CaseType), ref fCaseType, value); }
        }
    }

}
