//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GuncelYazılımCase.Module.BusinessObjects.Database
{

    public partial class DboCustomers : XPObject
    {
        string fCustomerName;
        public string CustomerName
        {
            get { return fCustomerName; }
            set { SetPropertyValue<string>(nameof(CustomerName), ref fCustomerName, value); }
        }
        string fCustomerSurname;
        public string CustomerSurname
        {
            get { return fCustomerSurname; }
            set { SetPropertyValue<string>(nameof(CustomerSurname), ref fCustomerSurname, value); }
        }
        string fCustomerTelephone;
        public string CustomerTelephone
        {
            get { return fCustomerTelephone; }
            set { SetPropertyValue<string>(nameof(CustomerTelephone), ref fCustomerTelephone, value); }
        }
        string fCustomerAddress;
        public string CustomerAddress
        {
            get { return fCustomerAddress; }
            set { SetPropertyValue<string>(nameof(CustomerAddress), ref fCustomerAddress, value); }
        }
        DboCustomerCompanies fCustomerCompany;
        [Association(@"CustomersReferencesCustomerCompanies")]
        public DboCustomerCompanies CustomerCompany
        {
            get { return fCustomerCompany; }
            set { SetPropertyValue<DboCustomerCompanies>(nameof(CustomerCompany), ref fCustomerCompany, value); }
        }
        [Association(@"CasesReferencesCustomers")]
        public XPCollection<DboCases> CasesCollection { get { return GetCollection<DboCases>(nameof(CasesCollection)); } }
    }

}
