//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GuncelYazılımCase.Module.BusinessObjects.Database
{

    public partial class DboCustomerCompanies : XPObject
    {
        string fCompanyName;
        public string CompanyName
        {
            get { return fCompanyName; }
            set { SetPropertyValue<string>(nameof(CompanyName), ref fCompanyName, value); }
        }
        string fCompanyAddress;
        public string CompanyAddress
        {
            get { return fCompanyAddress; }
            set { SetPropertyValue<string>(nameof(CompanyAddress), ref fCompanyAddress, value); }
        }
        string fCompanyTelephoneNumber;
        public string CompanyTelephoneNumber
        {
            get { return fCompanyTelephoneNumber; }
            set { SetPropertyValue<string>(nameof(CompanyTelephoneNumber), ref fCompanyTelephoneNumber, value); }
        }
        string fCompanySector;
        public string CompanySector
        {
            get { return fCompanySector; }
            set { SetPropertyValue<string>(nameof(CompanySector), ref fCompanySector, value); }
        }
        [Association(@"CustomersReferencesCustomerCompanies")]
        public XPCollection<DboCustomers> CustomersCollection { get { return GetCollection<DboCustomers>(nameof(CustomersCollection)); } }
    }

}
