//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GuncelYazılımCase.Module.BusinessObjects.Database
{

    public partial class DboEmployee : XPObject
    {
        string fEmployeeName;
        public string EmployeeName
        {
            get { return fEmployeeName; }
            set { SetPropertyValue<string>(nameof(EmployeeName), ref fEmployeeName, value); }
        }
        string fEmployeeSurname;
        public string EmployeeSurname
        {
            get { return fEmployeeSurname; }
            set { SetPropertyValue<string>(nameof(EmployeeSurname), ref fEmployeeSurname, value); }
        }
        string fEmployeeTelephone;
        public string EmployeeTelephone
        {
            get { return fEmployeeTelephone; }
            set { SetPropertyValue<string>(nameof(EmployeeTelephone), ref fEmployeeTelephone, value); }
        }
        string fEmployeeAddress;
        public string EmployeeAddress
        {
            get { return fEmployeeAddress; }
            set { SetPropertyValue<string>(nameof(EmployeeAddress), ref fEmployeeAddress, value); }
        }
        double fEmployeeSalary;
        public double EmployeeSalary
        {
            get { return fEmployeeSalary; }
            set { SetPropertyValue<double>(nameof(EmployeeSalary), ref fEmployeeSalary, value); }
        }
        DateTime fEmployeeStartDate;
        public DateTime EmployeeStartDate
        {
            get { return fEmployeeStartDate; }
            set { SetPropertyValue<DateTime>(nameof(EmployeeStartDate), ref fEmployeeStartDate, value); }
        }
        [Association(@"DboCasesReferencesDboEmployee")]
        public XPCollection<DboCases> DboCasesCollection { get { return GetCollection<DboCases>(nameof(DboCasesCollection)); } }
    }

}
