//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GuncelYazılımCase.Module.BusinessObjects.Database
{

    public partial class DboStatus : XPObject
    {
        string fStatu;
        public string Statu
        {
            get { return fStatu; }
            set { SetPropertyValue<string>(nameof(Statu), ref fStatu, value); }
        }
        [Association(@"CasesReferencesStatus")]
        public XPCollection<DboCases> CasesCollection { get { return GetCollection<DboCases>(nameof(CasesCollection)); } }
    }

}
